service: photovault-backend

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  stage: ${opt:stage, 'prod-v1'}
  profile: photovault-akhil-app-user

  iam:
    role: arn:aws:iam::278899968165:role/PhotoVaultLambdaRole

# No functions section — Lambda + API Gateway already exist, we update them via CLI

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: photovault-users-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: auth0Id
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: auth0Id-index
            KeySchema:
              - AttributeName: auth0Id
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    PhotosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: photovault-photos-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: photoId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
          - AttributeName: uploadedAt
            AttributeType: S
        KeySchema:
          - AttributeName: photoId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: userId-uploadedAt-index
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: uploadedAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

    AlbumsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: photovault-albums-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: albumId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
          - AttributeName: publicToken
            AttributeType: S
        KeySchema:
          - AttributeName: albumId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: userId-createdAt-index
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: createdAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: publicToken-index
            KeySchema:
              - AttributeName: publicToken
                KeyType: HASH
            Projection:
              ProjectionType: ALL

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001
    host: 0.0.0.0

package:
  patterns:
    - '!src/**'
    - '!**/*.test.ts'
    - '!jest.config.js'
    - 'dist/**'
    - 'node_modules/**'
